# Generated by Django 5.1.1 on 2024-09-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
            ],
            options={
                'verbose_name': 'Ambiance recherchée',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Editeur',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
                ('notes', models.CharField(max_length=2048, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
                ('order', models.IntegerField(unique=True, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
                ('order', models.IntegerField(unique=True, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom')),
                ('notes', models.CharField(max_length=512, verbose_name='notes')),
                ('box_img', models.CharField(max_length=2048, verbose_name='url image boîte')),
                ('box_content_img', models.CharField(max_length=2048, verbose_name='url image boîte contenu')),
                ('min_number_of_player', models.IntegerField(verbose_name='nombre de joueur minimum')),
                ('max_number_of_player', models.IntegerField(verbose_name='nombre de joueur maximum')),
                ('min_duration', models.IntegerField(verbose_name='durée minimum (minutes)')),
                ('max_duration', models.IntegerField(verbose_name='durée maximum (minutes)')),
                ('ambiances', models.ManyToManyField(to='games.ambiance', verbose_name='ambiance de jeu')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.editor', verbose_name='éditeur')),
                ('genres', models.ManyToManyField(to='games.genre', verbose_name='genre de jeu')),
                ('levels', models.ManyToManyField(to='games.level', verbose_name='niveau de jeu')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.tag', verbose_name='tag')),
                ('types', models.ManyToManyField(to='games.type', verbose_name='type de jeu')),
            ],
            options={
                'verbose_name': 'Jeu',
            },
        ),
    ]
