# Generated by Django 5.1.1 on 2024-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_notes_alter_genre_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="rules_link",
            field=models.CharField(max_length=2048, verbose_name="url vers les règles de jeu"),
            preserve_default=False,
        ),
    ]
