# Generated by Django 5.1.1 on 2024-09-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_rules_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiance',
            options={'verbose_name': 'ambiance recherchée', 'verbose_name_plural': 'ambiances recherchées'},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': 'éditeur', 'verbose_name_plural': 'éditeurs'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'jeu', 'verbose_name_plural': 'jeux'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'niveau', 'verbose_name_plural': 'niveaux'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
    ]
